---

##################################################################
#                                                                #
#               This tasks file defines the Projects             #
#                                                                #
##################################################################

  - name: Project
    os_project:
      auth:
        auth_url: "{{ auth_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      interface: admin
      state: "{{ state }}"
      name: "{{ project }}"
      description: "Project created via Ansible"
